name: xcanvas
channels:
  - conda-forge
dependencies:
  - cmake
  - cxx-compiler
  - xproperty
  - xwidgets >=0.28.1
  - ipycanvas >=0.11.0,<0.12
  - pytest
  - nbval
# TODO: replace xeus-cling with xeus(cpp when it is available
#- xeus-cling
